---
- hosts: all
  become: true
  tasks:
    - name: Importar rpm
      shell: rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
    - name: Criar repo
      copy:
        src: elastic.repo
        dest: /etc/yum.repos.d/
    - name: Instalar filebeat
      yum:
        name: filebeat
    - name: Deletar filebeat.yml padrao
      file:
        state: absent
        path: "/etc/filebeat/filebeat.yml"
    - name: Criar filebeat.yml
      template:
        src: templates/filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
    - name: Inicia filebeat
      service:
        name: filebeat
        state: restarted
        enabled: yes